name: Build Kernel                # ワークフロー名
on: push                          # イベント（プッシュ時に起動）
jobs:                             # ジョブの定義
  hello:                          # ジョブID
    runs-on: ubuntu-22.04         # ランナー（Ubuntuで実行）
    steps:                        # ステップの定義
      - run: uname -a             # シェルコマンドの実行
      - uses: actions/checkout@v4 # アクションの呼び出し

      - run: sudo apt install crossbuild-essential-arm64 bison flex python3-pycryptodome python3-pyelftools zlib1g-dev libssl-dev bc wireless-regdb atmark-firmware
      - run: wget https://armadillo.atmark-techno.com/files/downloads/alpine/v3.20/atmark/src/linux-at-x2-5.10.222-r0.tar
      - run: tar xf linux-at-x2-5.10.222-r0.tar
      - run: ls linux-at-x2-5.10.222-r0
      - run: cd linux-at-x2-5.10.222-r0 && tar xf linux-5.10-5.10.222-r0.tar.gz
      - run: cd linux-at-x2-5.10.222-r0/linux-5.10-5.10.222-r0 && make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- x2_defconfig
      - run: cd linux-at-x2-5.10.222-r0/linux-5.10-5.10.222-r0 && make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j5


