name: Hello                       # ワークフロー名
on: push                          # イベント（プッシュ時に起動）
jobs:                             # ジョブの定義
  hello:                          # ジョブID
    runs-on: ubuntu-22.04         # ランナー（Ubuntuで実行）
    steps:                        # ステップの定義
      - run: uname -a             # シェルコマンドの実行
      - uses: actions/checkout@v4 # アクションの呼び出し
